### Test Route
GET http://localhost:5000/test


### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Omkar Kumar",
  "email": "omkar@test.com",
  "password": "12345"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "omkar@test.com",
  "password": "12345"
}

